services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=easy_bank
    ports:
      - "3306:3306"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MIGRATE_DB_SOURCE=mysql://root:123@tcp(mysql:3306)/easy_bank?parseTime=true
    depends_on:
      - mysql
    entrypoint: ["/app/wait-for.sh", "mysql:3306","-t","120","--", "/app/start.sh"]