services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=easy_bank
    ports:
      - "3306:3306"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      # 컨테이너의 환경 변수를 app.env 내부 변수와 중복으로 지정하면 go-viper가 환경 변수를 읽어서 app.env을 덮어쓴다.
      - MIGRATE_DB_SOURCE=mysql://root:123@tcp(mysql:3306)/easy_bank?parseTime=true
      - DB_SOURCE=root:123@tcp(mysql:3306)/easy_bank?parseTime=true
    depends_on:
      - mysql
    entrypoint: ["/app/wait-for.sh", "mysql:3306","-t","120","--", "/app/start.sh"]